<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="55" failures="20" errors="0" time="26.319737">
	<testsuite tests="55" failures="20" time="0.000000" name="errors" timestamp="2024-04-25T15:10:59Z">
		<properties>
			<property name="go.version" value="go1.22.2 linux/arm64"></property>
		</properties>
		<testcase classname="errors" name="TestAs" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestAs&#xA;/home/vscode/.cache/tinygo/goroot-c2837f81ee81c8ecea884819967eafb31ba911b22ee551ef42f43b1105f0124e/src/errors/non-existing=== RUN   TestAs/0:As(Errorf(...,_&lt;nil&gt;),_0x45df0)&#xA;    --- PASS: TestAs/0:As(Errorf(...,_&lt;nil&gt;),_0x45df0) (0.00s)&#xA;--- FAIL: TestAs (0.03s)&#xA;=== RUN   TestAs/1:As(Errorf(...,_pitied_the_fool),_errorT())&#xA;    --- PASS: TestAs/1:As(Errorf(...,_pitied_the_fool),_errorT()) (0.00s)&#xA;=== RUN   TestAs/2:As(Errorf(...,_open_non-existing:_file_does_not_exist),_0x45df0)&#xA;    --- PASS: TestAs/2:As(Errorf(...,_open_non-existing:_file_does_not_exist),_0x45df0) (0.00s)&#xA;=== RUN   TestAs/3:As(Errorf(...,_errorT()),_0x45df0)&#xA;    --- PASS: TestAs/3:As(Errorf(...,_errorT()),_0x45df0) (0.00s)&#xA;=== RUN   TestAs/4:As(Errorf(...,_wrapped),_errorT(T))&#xA;    --- PASS: TestAs/4:As(Errorf(...,_wrapped),_errorT(T)) (0.00s)&#xA;=== RUN   TestAs/5:As(Errorf(...,_error),_errorT())&#xA;    --- PASS: TestAs/5:As(Errorf(...,_error),_errorT()) (0.00s)&#xA;=== RUN   TestAs/6:As(Errorf(...,_path),_0x45df0)&#xA;    --- PASS: TestAs/6:As(Errorf(...,_path),_0x45df0) (0.00s)&#xA;=== RUN   TestAs/7:As(Errorf(...,_oh_no),_0x45e10)&#xA;    --- PASS: TestAs/7:As(Errorf(...,_oh_no),_0x45e10) (0.00s)&#xA;=== RUN   TestAs/8:As(Errorf(...,_err),_0x45e00)&#xA;        match: got true; want false&#xA;        FailNow is incomplete, requires runtime.Goexit()&#xA;        got &amp;errors.errorString{s:&#34;err&#34;}, want &lt;nil&gt;&#xA;        FailNow is incomplete, requires runtime.Goexit()&#xA;    --- FAIL: TestAs/8:As(Errorf(...,_err),_0x45e00) (0.00s)&#xA;=== RUN   TestAs/9:As(Errorf(...,_open_non-existing:_file_does_not_exist),_0x45e00)&#xA;    --- PASS: TestAs/9:As(Errorf(...,_open_non-existing:_file_does_not_exist),_0x45e00) (0.00s)&#xA;=== RUN   TestAs/10:As(Errorf(...,_path_error),_0x45e00)&#xA;        got errors_test.wrapped{msg:&#34;path error&#34;, err:(*fs.PathError)(0x45f50)}, want &amp;fs.PathError{Op:&#34;open&#34;, Path:&#34;non-existing&#34;, Err:(*errors.errorString)(0x2703c)}&#xA;        FailNow is incomplete, requires runtime.Goexit()&#xA;    --- FAIL: TestAs/10:As(Errorf(...,_path_error),_0x45e00) (0.00s)&#xA;=== RUN   TestAs/11:As(Errorf(...,_multiError),_errorT(poser))&#xA;    --- PASS: TestAs/11:As(Errorf(...,_multiError),_errorT(poser)) (0.00s)&#xA;=== RUN   TestAs/12:As(Errorf(...,_multiError),_errorT())&#xA;    --- PASS: TestAs/12:As(Errorf(...,_multiError),_errorT()) (0.00s)&#xA;=== RUN   TestAs/13:As(Errorf(...,_multiError),_errorT(T))&#xA;    --- PASS: TestAs/13:As(Errorf(...,_multiError),_errorT(T)) (0.00s)&#xA;=== RUN   TestAs/14:As(Errorf(...,_multiError),_errorT(T))&#xA;    --- PASS: TestAs/14:As(Errorf(...,_multiError),_errorT(T)) (0.00s)&#xA;=== RUN   TestAs/15:As(Errorf(...,_multiError),_errorT(a))&#xA;    --- PASS: TestAs/15:As(Errorf(...,_multiError),_errorT(a)) (0.00s)&#xA;=== RUN   TestAs/16:As(Errorf(...,_multiError),_0x45e00)&#xA;        got errors_test.multiErr{errors_test.wrapped{msg:&#34;path error&#34;, err:(*fs.PathError)(0x45f50)}}, want &amp;fs.PathError{Op:&#34;open&#34;, Path:&#34;non-existing&#34;, Err:(*errors.errorString)(0x2703c)}&#xA;        FailNow is incomplete, requires runtime.Goexit()&#xA;    --- FAIL: TestAs/16:As(Errorf(...,_multiError),_0x45e00) (0.00s)&#xA;=== RUN   TestAs/17:As(Errorf(...,_multiError),_errorT(a))&#xA;    --- PASS: TestAs/17:As(Errorf(...,_multiError),_errorT(a)) (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="errors" name="TestAs/6:As(Errorf(...,_path),_0x45df0)" time="-0.000000">
			<failure message="Failed" type="">=== RUN   TestAs/6:As(Errorf(...,_path),_0x45df0)&#xA;    --- PASS: TestAs/6:As(Errorf(...,_path),_0x45df0) (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="errors" name="TestAs/9:As(Errorf(...,_open_non-existing:_file_does_not_exist),_0x45e00)" time="-0.000000">
			<failure message="Failed" type="">=== RUN   TestAs/9:As(Errorf(...,_open_non-existing:_file_does_not_exist),_0x45e00)&#xA;    --- PASS: TestAs/9:As(Errorf(...,_open_non-existing:_file_does_not_exist),_0x45e00) (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="errors" name="TestAs/13:As(Errorf(...,_multiError),_errorT(T))" time="-0.000000">
			<failure message="Failed" type="">=== RUN   TestAs/13:As(Errorf(...,_multiError),_errorT(T))&#xA;    --- PASS: TestAs/13:As(Errorf(...,_multiError),_errorT(T)) (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="errors" name="TestAs/7:As(Errorf(...,_oh_no),_0x45e10)" time="-0.000000">
			<failure message="Failed" type="">=== RUN   TestAs/7:As(Errorf(...,_oh_no),_0x45e10)&#xA;    --- PASS: TestAs/7:As(Errorf(...,_oh_no),_0x45e10) (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="errors" name="TestAs/8:As(Errorf(...,_err),_0x45e00)" time="-0.000000">
			<failure message="Failed" type="">=== RUN   TestAs/8:As(Errorf(...,_err),_0x45e00)&#xA;        match: got true; want false&#xA;        FailNow is incomplete, requires runtime.Goexit()&#xA;        got &amp;errors.errorString{s:&#34;err&#34;}, want &lt;nil&gt;&#xA;        FailNow is incomplete, requires runtime.Goexit()&#xA;    --- FAIL: TestAs/8:As(Errorf(...,_err),_0x45e00) (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="errors" name="TestAs/12:As(Errorf(...,_multiError),_errorT())" time="-0.000000">
			<failure message="Failed" type="">=== RUN   TestAs/12:As(Errorf(...,_multiError),_errorT())&#xA;    --- PASS: TestAs/12:As(Errorf(...,_multiError),_errorT()) (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="errors" name="TestAs/14:As(Errorf(...,_multiError),_errorT(T))" time="-0.000000">
			<failure message="Failed" type="">=== RUN   TestAs/14:As(Errorf(...,_multiError),_errorT(T))&#xA;    --- PASS: TestAs/14:As(Errorf(...,_multiError),_errorT(T)) (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="errors" name="TestAs/15:As(Errorf(...,_multiError),_errorT(a))" time="-0.000000">
			<failure message="Failed" type="">=== RUN   TestAs/15:As(Errorf(...,_multiError),_errorT(a))&#xA;    --- PASS: TestAs/15:As(Errorf(...,_multiError),_errorT(a)) (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="errors" name="TestAsValidation/&lt;nil&gt;(&lt;nil&gt;)" time="-0.000000">
			<failure message="Failed" type="">=== RUN   TestAsValidation/&lt;nil&gt;(&lt;nil&gt;)&#xA;panic: errors: target cannot be nil&#xA;Error: failed to run main module `/tmp/tinygo3702875242/main`&#xA;&#xA;Caused by:&#xA;    0: failed to invoke `run` function&#xA;    1: error while executing at wasm backtrace:&#xA;           0: 0x32a2 - runtime.abort&#xA;                           at /workspaces/dc-wasm-go/tinygo/src/runtime/runtime_tinygowasmp2.go:59:6              - runtime._panic&#xA;                           at /workspaces/dc-wasm-go/tinygo/src/runtime/panic.go:65:7&#xA;           1: 0x1030c - (Go interface method)&#xA;                           at /usr/local/go/src/errors/wrap.go:102:8              - errors.As&#xA;                           at /usr/local/go/src/errors/wrap.go:109:24&#xA;           2: 0x757fd - errors_test.TestAsValidation$1&#xA;                           at /usr/local/go/src/errors/wrap_test.go:232:22&#xA;           3: 0x2afd9 - testing.tRunner&#xA;                           at /workspaces/dc-wasm-go/tinygo/src/testing/testing.go:427:4&#xA;           4: 0x56ce1 - (*testing.T).Run&#xA;           5: 0x75642 - errors_test.TestAsValidation&#xA;                           at /usr/local/go/src/errors/wrap_test.go:228:8&#xA;           6: 0x2afd9 - testing.tRunner&#xA;                           at /workspaces/dc-wasm-go/tinygo/src/testing/testing.go:427:4&#xA;           7: 0x56ce1 - (*testing.T).Run&#xA;           8: 0x2ace1 - testing.runTests$1&#xA;                           at /workspaces/dc-wasm-go/tinygo/src/testing/testing.go:561:10&#xA;           9: 0x2afd9 - testing.tRunner&#xA;                           at /workspaces/dc-wasm-go/tinygo/src/testing/testing.go:427:4&#xA;          10: 0x25fbb - &lt;unknown&gt;!runtime.run$1&#xA;          11: 0x1913b - &lt;goroutine wrapper&gt;&#xA;                           at /workspaces/dc-wasm-go/tinygo/src/runtime/scheduler_any.go:23:2&#xA;          12: 0x1965 - tinygo_launch&#xA;                           at /workspaces/dc-wasm-go/tinygo/src/internal/task/task_asyncify_wasm.S:59&#xA;          13: 0x18fee - (*internal/task.Task).Resume&#xA;                           at /workspaces/dc-wasm-go/tinygo/src/internal/task/task_asyncify.go:109:17              - runtime.scheduler&#xA;                           at /workspaces/dc-wasm-go/tinygo/src/runtime/scheduler.go:236:11              - runtime.run&#xA;                           at /workspaces/dc-wasm-go/tinygo/src/runtime/scheduler_any.go:28:11              - _start&#xA;                           at /workspaces/dc-wasm-go/tinygo/src/runtime/runtime_wasm_wasip2.go:30:5&#xA;          14: 0x18d65 - wasi:cli/run@0.2.0#run&#xA;                           at /workspaces/dc-wasm-go/tinygo/src/runtime/runtime_wasm_wasip2.go:21:8&#xA;    2: wasm trap: wasm `unreachable` instruction executed&#xA;</failure>
		</testcase>
		<testcase classname="errors" name="TestAs/10:As(Errorf(...,_path_error),_0x45e00)" time="-0.000000">
			<failure message="Failed" type="">=== RUN   TestAs/10:As(Errorf(...,_path_error),_0x45e00)&#xA;        got errors_test.wrapped{msg:&#34;path error&#34;, err:(*fs.PathError)(0x45f50)}, want &amp;fs.PathError{Op:&#34;open&#34;, Path:&#34;non-existing&#34;, Err:(*errors.errorString)(0x2703c)}&#xA;        FailNow is incomplete, requires runtime.Goexit()&#xA;    --- FAIL: TestAs/10:As(Errorf(...,_path_error),_0x45e00) (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="errors" name="TestAs/2:As(Errorf(...,_open_non-existing:_file_does_not_exist),_0x45df0)" time="-0.000000">
			<failure message="Failed" type="">=== RUN   TestAs/2:As(Errorf(...,_open_non-existing:_file_does_not_exist),_0x45df0)&#xA;    --- PASS: TestAs/2:As(Errorf(...,_open_non-existing:_file_does_not_exist),_0x45df0) (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="errors" name="TestAs/3:As(Errorf(...,_errorT()),_0x45df0)" time="-0.000000">
			<failure message="Failed" type="">=== RUN   TestAs/3:As(Errorf(...,_errorT()),_0x45df0)&#xA;    --- PASS: TestAs/3:As(Errorf(...,_errorT()),_0x45df0) (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="errors" name="TestAs/4:As(Errorf(...,_wrapped),_errorT(T))" time="-0.000000">
			<failure message="Failed" type="">=== RUN   TestAs/4:As(Errorf(...,_wrapped),_errorT(T))&#xA;    --- PASS: TestAs/4:As(Errorf(...,_wrapped),_errorT(T)) (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="errors" name="TestAs/16:As(Errorf(...,_multiError),_0x45e00)" time="-0.000000">
			<failure message="Failed" type="">=== RUN   TestAs/16:As(Errorf(...,_multiError),_0x45e00)&#xA;        got errors_test.multiErr{errors_test.wrapped{msg:&#34;path error&#34;, err:(*fs.PathError)(0x45f50)}}, want &amp;fs.PathError{Op:&#34;open&#34;, Path:&#34;non-existing&#34;, Err:(*errors.errorString)(0x2703c)}&#xA;        FailNow is incomplete, requires runtime.Goexit()&#xA;    --- FAIL: TestAs/16:As(Errorf(...,_multiError),_0x45e00) (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="errors" name="TestAs/17:As(Errorf(...,_multiError),_errorT(a))" time="-0.000000">
			<failure message="Failed" type="">=== RUN   TestAs/17:As(Errorf(...,_multiError),_errorT(a))&#xA;    --- PASS: TestAs/17:As(Errorf(...,_multiError),_errorT(a)) (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="errors" name="TestAs/1:As(Errorf(...,_pitied_the_fool),_errorT())" time="-0.000000">
			<failure message="Failed" type="">=== RUN   TestAs/1:As(Errorf(...,_pitied_the_fool),_errorT())&#xA;    --- PASS: TestAs/1:As(Errorf(...,_pitied_the_fool),_errorT()) (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="errors" name="TestAs/5:As(Errorf(...,_error),_errorT())" time="-0.000000">
			<failure message="Failed" type="">=== RUN   TestAs/5:As(Errorf(...,_error),_errorT())&#xA;    --- PASS: TestAs/5:As(Errorf(...,_error),_errorT()) (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="errors" name="TestAs/11:As(Errorf(...,_multiError),_errorT(poser))" time="-0.000000">
			<failure message="Failed" type="">=== RUN   TestAs/11:As(Errorf(...,_multiError),_errorT(poser))&#xA;    --- PASS: TestAs/11:As(Errorf(...,_multiError),_errorT(poser)) (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="errors" name="TestAsValidation" time="-0.000000">
			<failure message="Failed" type="">=== RUN   TestAsValidation&#xA;=== RUN   TestAsValidation/&lt;nil&gt;(&lt;nil&gt;)&#xA;panic: errors: target cannot be nil&#xA;Error: failed to run main module `/tmp/tinygo3702875242/main`&#xA;&#xA;Caused by:&#xA;    0: failed to invoke `run` function&#xA;    1: error while executing at wasm backtrace:&#xA;           0: 0x32a2 - runtime.abort&#xA;                           at /workspaces/dc-wasm-go/tinygo/src/runtime/runtime_tinygowasmp2.go:59:6              - runtime._panic&#xA;                           at /workspaces/dc-wasm-go/tinygo/src/runtime/panic.go:65:7&#xA;           1: 0x1030c - (Go interface method)&#xA;                           at /usr/local/go/src/errors/wrap.go:102:8              - errors.As&#xA;                           at /usr/local/go/src/errors/wrap.go:109:24&#xA;           2: 0x757fd - errors_test.TestAsValidation$1&#xA;                           at /usr/local/go/src/errors/wrap_test.go:232:22&#xA;           3: 0x2afd9 - testing.tRunner&#xA;                           at /workspaces/dc-wasm-go/tinygo/src/testing/testing.go:427:4&#xA;           4: 0x56ce1 - (*testing.T).Run&#xA;           5: 0x75642 - errors_test.TestAsValidation&#xA;                           at /usr/local/go/src/errors/wrap_test.go:228:8&#xA;           6: 0x2afd9 - testing.tRunner&#xA;                           at /workspaces/dc-wasm-go/tinygo/src/testing/testing.go:427:4&#xA;           7: 0x56ce1 - (*testing.T).Run&#xA;           8: 0x2ace1 - testing.runTests$1&#xA;                           at /workspaces/dc-wasm-go/tinygo/src/testing/testing.go:561:10&#xA;           9: 0x2afd9 - testing.tRunner&#xA;                           at /workspaces/dc-wasm-go/tinygo/src/testing/testing.go:427:4&#xA;          10: 0x25fbb - &lt;unknown&gt;!runtime.run$1&#xA;          11: 0x1913b - &lt;goroutine wrapper&gt;&#xA;                           at /workspaces/dc-wasm-go/tinygo/src/runtime/scheduler_any.go:23:2&#xA;          12: 0x1965 - tinygo_launch&#xA;                           at /workspaces/dc-wasm-go/tinygo/src/internal/task/task_asyncify_wasm.S:59&#xA;          13: 0x18fee - (*internal/task.Task).Resume&#xA;                           at /workspaces/dc-wasm-go/tinygo/src/internal/task/task_asyncify.go:109:17              - runtime.scheduler&#xA;                           at /workspaces/dc-wasm-go/tinygo/src/runtime/scheduler.go:236:11              - runtime.run&#xA;                           at /workspaces/dc-wasm-go/tinygo/src/runtime/scheduler_any.go:28:11              - _start&#xA;                           at /workspaces/dc-wasm-go/tinygo/src/runtime/runtime_wasm_wasip2.go:30:5&#xA;          14: 0x18d65 - wasi:cli/run@0.2.0#run&#xA;                           at /workspaces/dc-wasm-go/tinygo/src/runtime/runtime_wasm_wasip2.go:21:8&#xA;    2: wasm trap: wasm `unreachable` instruction executed&#xA;</failure>
		</testcase>
		<testcase classname="errors" name="TestNewEqual" time="0.000000"></testcase>
		<testcase classname="errors" name="TestErrorMethod" time="0.000000"></testcase>
		<testcase classname="errors" name="TestJoinReturnsNil" time="0.000000"></testcase>
		<testcase classname="errors" name="TestJoin" time="0.000000"></testcase>
		<testcase classname="errors" name="TestJoinErrorMethod" time="0.000000"></testcase>
		<testcase classname="errors" name="TestIs" time="0.000000"></testcase>
	</testsuite>
</testsuites>